/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/Views/**/*.php",
    "./public/js/**/*.js",
  ],
  safelist: [
    // Background colors
    'bg-white',
    'bg-gray-50',
    'bg-gray-100',
    'bg-gray-200',
    'bg-blue-50',
    'bg-blue-100',
    'bg-green-50',
    'bg-green-100',
    'bg-green-600',
    'bg-green-700',
    'bg-red-50',
    'bg-red-100',
    'bg-red-600',
    'bg-yellow-50',
    'bg-yellow-100',
    'bg-yellow-400',
    'bg-yellow-500',
    'bg-purple-100',
    'bg-gradient-to-br',
    'bg-gradient-to-r',
    'from-[#182919]',
    'via-[#243C25]',
    'to-[#345635]',
    'from-transparent',
    'to-[#D1EEB8]',
    
    // Text colors
    'text-white',
    'text-gray-500',
    'text-gray-600',
    'text-gray-700',
    'text-gray-800',
    'text-gray-900',
    'text-red-600',
    'text-red-700',
    'text-green-600',
    'text-green-700',
    'text-green-800',
    'text-blue-500',
    'text-blue-600',
    'text-blue-700',
    'text-yellow-600',
    'text-yellow-700',
    'text-yellow-800',
    'text-purple-600',
    'text-[#022E23]',
    'text-[#044031]',
    'text-[#5c7a5c]',
    
    // Padding
    'p-1',
    'p-2',
    'p-3',
    'p-4',
    'p-5',
    'p-6',
    'p-8',
    'px-2',
    'px-3',
    'px-4',
    'px-6',
    'py-1',
    'py-1.5',
    'py-2',
    'py-3',
    'py-4',
    'py-8',
    'py-12',
    
    // Margin
    'm-1',
    'm-2',
    'm-3',
    'm-4',
    'mx-auto',
    'my-4',
    'my-6',
    'mt-1',
    'mt-2',
    'mt-3',
    'mt-4',
    'mt-6',
    'mb-1',
    'mb-2',
    'mb-3',
    'mb-4',
    'mb-6',
    'ml-1',
    'ml-2',
    'ml-4',
    'mr-2',
    'gap-1',
    'gap-2',
    'gap-3',
    'gap-4',
    'gap-6',
    
    // Borders
    'border',
    'border-0',
    'border-2',
    'border-t',
    'border-b',
    'border-gray-200',
    'border-gray-300',
    'border-green-300',
    'border-green-400',
    'border-red-400',
    'border-blue-600',
    'border-blue-300',
    'border-yellow-300',
    'border-red-300',
    'border-[#d4dfd4]',
    'border-white/10',
    
    // Rounded
    'rounded',
    'rounded-md',
    'rounded-lg',
    'rounded-xl',
    'rounded-2xl',
    'rounded-full',
    
    // Shadows
    'shadow-sm',
    'shadow-md',
    'shadow-lg',
    'shadow-xl',
    'shadow-2xl',
    'shadow-inner',
    'shadow-[0_0_0_3px_rgba(251,191,36,0.25)]',
    'hover:shadow-md',
    'hover:shadow-lg',
    'hover:shadow-[0_20px_60px_rgba(0,0,0,0.5)]',
    
    // Flex & Grid
    'flex',
    'flex-1',
    'flex-col',
    'flex-wrap',
    'inline-flex',
    'grid',
    'grid-cols-1',
    'grid-cols-2',
    'grid-cols-3',
    'md:grid-cols-2',
    'md:grid-cols-3',
    'md:grid-cols-4',
    'lg:grid-cols-3',
    'lg:grid-cols-4',
    'xl:grid-cols-5',
    'gap-2',
    'gap-3',
    'gap-4',
    'gap-6',
    'space-y-2',
    'space-y-5',
    
    // Width & Height
    'w-full',
    'w-4',
    'w-8',
    'w-2',
    'h-4',
    'h-8',
    'h-20',
    'h-px',
    'h-screen',
    'h-full',
    'min-h-screen',
    'max-w-md',
    'max-w-sm',
    'max-w-4xl',
    'max-w-[150px]',
    'max-w-[200px]',
    'max-w-[350px]',
    'max-h-[90vh]',
    'aspect-square',
    
    // Transitions
    'transition',
    'transition-all',
    'transition-shadow',
    'transition-transform',
    'duration-200',
    'duration-300',
    'hover:scale-[1.02]',
    
    // Position
    'fixed',
    'absolute',
    'relative',
    'static',
    'inset-0',
    'top-0',
    'right-0',
    'top-4',
    'right-4',
    'z-[1100]',
    'pointer-events-none',
    
    // Other utilities
    'block',
    'inline-block',
    'hidden',
    'overflow-hidden',
    'overflow-x-auto',
    'overflow-y-auto',
    'whitespace-nowrap',
    'truncate',
    'text-center',
    'text-left',
    'text-right',
    'text-sm',
    'text-xs',
    'text-xl',
    'text-2xl',
    'text-4xl',
    'text-6xl',
    'font-medium',
    'font-semibold',
    'font-bold',
    'font-extrabold',
    'list-disc',
    'list-inside',
    'leading-none',
    'capitalize',
    'opacity-80',
    'outline-none',
    'focus:ring-1',
    'focus:ring-4',
    'focus:ring-green-500',
    'focus:border-green-500',
    'focus:border-yellow-400',
    'focus:ring-yellow-200/50',
    'focus:bg-white',
    'focus:ring-red-500',
    'focus:border-red-500',
    'hover:bg-green-100',
    'hover:bg-green-700',
    'hover:bg-blue-50',
    'hover:bg-blue-700',
    'hover:bg-red-50',
    'hover:bg-red-700',
    'hover:bg-yellow-50',
    'hover:bg-gray-50',
    'hover:bg-gray-400',
    'hover:bg-gray-600',
    'hover:bg-white/10',
    'hover:text-blue-600',
    'hover:text-gray-200',
    'hover:text-gray-700',
    'hover:-translate-y-1',
    'hover:border-green-600',
    'hover:shadow-md',
    'drop-shadow-lg',
  ],
  theme: {
    extend: {},
  },
  plugins: [],
}